### ISSUE TITLE
license ?

### ISSUE THREAD

**Issue by nqzero** [bradforj287/SimpleTextSearch#2]
there doesn't appear to be a license specified in either a license file or in the source files. was your intention to license this library under a FOSS license ?

**Comment by bradforj287** [comment]
Yes, my intention was that this should be free software for anyone to use for any reason. Do you have a recommended next step?

**Comment by nqzero** [comment]
you need to pick a license - MIT and Apache are probably the most common in the java ecosystem. they're both liberal non-copyleft licenses - MIT is simpler and easier to fork/contribute to, but doesn't address patents explicitly. doesn't seem like a problem in this case, so i'd go with that one

copy the license file to your top level directory as LICENSE.txt

some people place a note in each source file pointing to the license, but i usually just add a note in my readme explicitly stating that all the included files are licensed according to the LICENSE.txt file

https://help.github.com/articles/licensing-a-repository/

if you choose one of the common licenses, github will detect it and display the license at the top of the page

**Comment by bradforj287** [comment]
i added the MIT license file

**Comment by nqzero** [comment]
one complication is that the stanford nlp package is GPL licensed. i didn't realize this when we had our earlier discussion. the MIT license is compatible with the GPL, so that's ok. but for users of the library, the GPL would infect their code (i [switched out the stanford tokenizer for the lucene one](https://github.com/nqzero/cruden/blob/100d8576fc70dd42414b1dbb7c12b8ae744c3a3e/src/main/java/com/nqzero/cruden/BaseInverted.java#L60) to work around this)

so it probably makes sense to add a note to the readme. if you'd like, i can submit a pull request to that effect

**Comment by bradforj287** [comment]
Good catch. Feel free to submit your pull request with the library change.
